---
title: "WL2_Mortality"
author: "Brandie Quarles"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Mortality at WL2

## Libraries 
```{r}
library(tidyverse)
```

## Load the libraries
```{r}
mort_pheno_0716 <- read_csv("../input/WL2_2024_Data/WL2_Mort_Pheno Survey_Order_Fixed_0716.csv") %>% 
  select(status:death.date)
head(mort_pheno_0716)
```

Pop/Loc Info for pop.type
```{r}
pop_loc <- read_csv("../input/WL2_2024_Data/WL2_Final_2023_2024_Pop_Loc_Info.csv") %>% 
  rename(row=bedrow, col=bedcol)
head(pop_loc)
```

Merge
```{r}
mort_pheno_0716_pops <- left_join(pop_loc, mort_pheno_0716)
head(mort_pheno_0716_pops)
```

## By pop type 
```{r}
unique(mort_pheno_0716_pops$Pop.Type)

by_pop_type <- mort_pheno_0716_pops %>% 
  filter(!is.na(Pop.Type)) %>% 
  group_by(Pop.Type) %>% 
  summarise(Alive=sum(is.na(death.date)), Dead=sum(!is.na(death.date))) %>% 
  mutate(mort = Dead/(Alive+Dead))
by_pop_type

by_pop_type %>% 
  filter(Pop.Type != "2023-TM2-fruit") %>% 
  ggplot(aes(x=Pop.Type, y=mort, fill=Pop.Type)) +
  geom_col() +
  ylim(0,1)

```

## By population
```{r}
by_pop <- mort_pheno_0716_pops %>% 
  group_by(pop, Pop.Type) %>% 
  summarise(Alive=sum(is.na(death.date)), Dead=sum(!is.na(death.date))) %>% 
  mutate(mort = Dead/(Alive+Dead))
by_pop %>% arrange(mort)

by_pop %>% 
  filter(Pop.Type == "Parent") %>% 
  ggplot(aes(fct_reorder(pop, mort), mort)) + 
  geom_col() +
  labs(x="Population", y="Proportion Dead")

by_pop %>% 
  filter(Pop.Type == "F1") %>% 
  ggplot(aes(fct_reorder(pop, mort), mort)) + 
  geom_col() +
  labs(x="Population", y="Proportion Dead") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

by_pop %>% 
  filter(Pop.Type == "F2") %>% 
  ggplot(aes(fct_reorder(pop, mort), mort)) + 
  geom_col() +
  labs(x="Population", y="Proportion Dead") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Parents colored by elevation
```{r}
by_pop_parents <- by_pop %>% 
  filter(Pop.Type == "Parent")

elev_info <- read_csv("../input/Strep_tort_locs.csv")

elev_info_yo <- elev_info %>% mutate(pop = str_replace(`Site code`, "YOSE(\\d+)", "YO\\1")) %>% select(Lat, Long, elev_m=`Elevation (m)`, pop)
head(elev_info_yo)
unique(elev_info_yo$pop)

by_pop_parents_elev <- left_join(by_pop_parents, elev_info_yo)
head(by_pop_parents_elev)

by_pop_parents_elev %>% 
  ggplot(aes(x=fct_reorder(pop, mort), y=mort, fill=elev_m)) + 
  geom_col(width = 0.7,position = position_dodge(0.75)) +
  labs(x="Population", y="Proportion Dead", fill="Elevation (m)") +
  theme_classic() + 
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_gradient(low = "#F5A540", high = "#0043F0") +
  theme(text=element_text(size=25))
ggsave("../output/WL2_Traits/WL2_Mortality_0716_Parents.png", width = 14, height = 8, units = "in")
```


## Over Time
Would need to calculate proportion dead for each census week for each population 

