---
title: "WL2_2024Plants_SurvtoRep-2025"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Survival to Rep of plants planted in 2024 

## Libraries
```{r}
library(tidyverse)

sem <- function(x, na.rm=FALSE) {           #for calculating standard error
  sd(x,na.rm=na.rm)/sqrt(length(na.omit(x)))
} 
```

## Load data

## Mort/pheno
```{r}
mort_pheno_2025 <- read_csv("../input/WL2_2025_Data/CorrectedCSVs/WL2_mort_pheno_20250929_corrected.csv")
mort_pheno_2025 %>% filter(!is.na(Unique.ID), Unique.ID!="buffer") %>% filter(is.na(as.numeric(Unique.ID))) #only non-numeric ID is yose plant from 2023
```

## Pop Info 
```{r}
pop_info_2025 <- read_csv("../input/WL2_2025_Data/2025_Pop_Loc_Info Updated.csv") %>% 
  select(status:Unique.ID)
```

## Elevation Info / Climate distance
```{r}
clim_dist_2024 <- read_csv("../output/Climate/WL2_2024_Clim_Dist.csv") %>% select(-conf.low, -conf.high)
head(clim_dist_2024)

clim_dist_2024_wide <- clim_dist_2024 %>% 
  pivot_wider(names_from = timeframe, values_from = Gowers_Dist, names_prefix = "GD_") %>% 
  rename(pop=parent.pop)
```

## Merge
```{r}
mort_pheno_2025_pops <- mort_pheno_2025 %>% 
  select(bed:Unique.ID, bud.date, death.date) %>% 
  left_join(pop_info_2025) %>% 
  filter(Unique.ID!="buffer", !is.na(Unique.ID))
```

## 2024 Plants Only
```{r}
mort_pheno_2025_pops_2024plants <- mort_pheno_2025_pops %>% 
  filter(status=="2024-survivor") %>% 
  mutate(Pop.Type=if_else(str_detect(pop.id, "\\) x"), "F2",
                          if_else(str_detect(pop.id, "x"), "F1",
                                  "Parent"
                          )))
dim(mort_pheno_2025_pops_2024plants) #only 78 plants - lost one?
xtabs(~Pop.Type, data=mort_pheno_2025_pops_2024plants) #one F2 missing - INVESTIGATE THIS LATER!!

mort_pheno_2025_pops_2024plants %>% filter(is.na(bud.date)) #only 5 plants did not initiate rep 
#2 BH  
#2 WL2 BC1s (with TM2 and YO11)
#1 F1 (WV x TM2)
```

## Surv to Budding of 2024 Plants
```{r}
repsurv_2024plants <- mort_pheno_2025_pops_2024plants %>% 
  select(Pop.Type, bed:col, pop.id:rep, Unique.ID:death.date) %>% 
  mutate(Surv_to_Rep = if_else(is.na(bud.date), 0, 1)) 
```

## Plot by pop type 
```{r}
repsurv_2024plants %>% 
  group_by(Pop.Type) %>% 
  summarise(meanSurv=mean(Surv_to_Rep), semSurv=sem(Surv_to_Rep)) %>% 
  ggplot(aes(x=Pop.Type, y=meanSurv)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=meanSurv-semSurv,ymax=meanSurv+semSurv),width=.2, position = 
                  position_dodge(0.75)) +
  theme_classic() + 
  scale_y_continuous(expand = c(0.01, 0.02), limits = c(-0.01, 1.08)) +
  labs(y="Survival to Budding", x="Population Type", , title="Population Categories") +
  annotate("text", x = 1, y= 1.04, label = "12 in May") +
  annotate("text", x = 2, y= 1.04, label = "45 in May") +
  annotate("text", x = 3, y= 1.04, label = "21 in May") +
  theme(text=element_text(size=25))
ggsave("../output/WL2_Traits/WL2_RepSurv_2024Plants_PopType.png", width = 10, height = 8, units = "in")
```