---
title: "WL2_2024_Full_DataSheet"
author: "Brandie Quarles"
date: "`r Sys.Date()`"
output: html_document
---

Note the error in the final code chunk for the handling of maternal family

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
bed_map_2024 <- read_csv("../input/Summer_24_Planting_Planning - Buffer New Bed Map.csv")
head(bed_map_2024)
names(bed_map_2024)
unique(bed_map_2024$status)

final_positions_2023 <- read_csv("../input/Pops for 2023 WL2 - 6_3_24 Survival Check.csv")
head(final_positions_2023)
names(final_positions_2023)
```
```{r}
bed_map_2024_prep <- bed_map_2024 %>% 
  #filter(status=="2023-survivor" | status=="2023-TM2-fruit") %>% 
  select(block, bed, bedrow, bedcol=column, status, pop=pop.id, rep, unique.ID) %>% 
  mutate(bed=toupper(bed))


final_positions_2023_prep <- final_positions_2023 %>% 
  select(bed.block.order:column.order, bed, bedrow=`bed-row`,bedcol=`bed-col`, pop, mf, rep) %>% 
  unite("unique.ID", pop:mf, remove = FALSE)

merge1 <- left_join(bed_map_2024_prep, final_positions_2023_prep, by=c("bed", "bedrow", "bedcol")) %>% 
  arrange(bed, AB.CD.order, bedrow, bedcol) %>% 
  mutate(unique.ID.x=as.character(unique.ID.x), rep.x=as.character(rep.x)) %>% 
  mutate(unique.ID=if_else(is.na(unique.ID.x), unique.ID.y, unique.ID.x),
         rep=if_else(is.na(unique.ID.x), rep.y, rep.x),
         pop=if_else(is.na(unique.ID.x), pop.y, pop.x))
head(merge1)
merge1 %>% filter(status=="available")
merge1 %>% filter(status=="2023-TM2-fruit")
merge1 %>% filter(status=="2023-survivor")
merge1 %>% filter(status=="out-of-bounds")

to_export <- merge1 %>% 
  select(bed.block.order:column.order, status, block:bedcol, pop, mf, rep, unique.ID) %>% 
  filter(status!="out-of-bounds") %>% 
  mutate(pop=if_else(status=="buffer", NA, pop),
         mf=if_else(status=="buffer", NA, mf), ###*Note: this does not account for the new 2024 plants not having mf info so this leaves 2023 mf info on those rows which is wrong!!
         rep=if_else(status=="buffer", NA, rep),
         unique.ID=if_else(status=="buffer", NA, unique.ID))
write_csv(to_export, "../output/WL2_2023_2024_MERGE.csv")
```

