---
title: "WL2_2025_Size_Rep"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Checking size at reproduction for plants planted in 2025 that flowered in their first year 

## Libraries
```{r}
library(tidyverse)
library(lmerTest)

sem <- function(x, na.rm=FALSE) {           #for calculating standard error
  sd(x,na.rm=na.rm)/sqrt(length(na.omit(x)))
} 
```

## Mort/pheno
```{r}
pheno_2025 <- read_csv("../input/WL2_2025_Data/CorrectedCSVs/WL2_mort_pheno_20250929_corrected.csv")
pheno_2025 %>% filter(!is.na(Unique.ID), Unique.ID!="buffer") %>% filter(is.na(as.numeric(Unique.ID))) #only non-numeric ID is yose plant from 2023
```

## Pop Info 
```{r}
pop_info_2025 <- read_csv("../input/WL2_2025_Data/2025_Pop_Loc_Info Updated.csv") %>% 
  select(status:Unique.ID)
```

## Merge
```{r}
pheno_2025_pops <- pheno_2025 %>% 
  select(bed:Unique.ID, flower.date, death.date) %>% 
  left_join(pop_info_2025) %>% 
  filter(Unique.ID!="buffer", !is.na(Unique.ID))

unique(pheno_2025_pops$status)
```

## 2025 Size 
```{r}
size_2025 <- dir("../input/WL2_2025_Data/CorrectedCSVs",
             pattern="WL2_size_survey.*corrected.*csv",
             full.names=TRUE)

size_2025_dat_wl2 <- tibble(path=size_2025, filename=basename(path)) %>% 
  mutate(survey_date=str_extract(filename, "20[0-9]*"),
         survey_date=lubridate::ymd(survey_date))
size_2025_dat_wl2

size_2025_dat_wl22 <- size_2025_dat_wl2 %>%
  mutate(sheets=map(path, 
                    read_csv,
                    na = c("", "NA", "-", "N/A") # sets NA strings. 
                    )) %>%
  select(-path)

#check for data issues
#map(size_2025_dat_wl22$sheets, colnames) %>% #get unique column names 
#  unlist() %>%
#  unique() %>%
#  sort() 
#lots of survey dates 
map(size_2025_dat_wl22$sheets, head,10) #look at first 10 lines of each sheet 
#no issues 

all_2025_size <- size_2025_dat_wl22 %>% 
  unnest(sheets) %>% 
  select(bed, col, row, Unique.ID, survey_date, height.cm)
names(all_2025_size)
```

## Size at Flowering (Individual Level)
```{r}
sizeatrep_2025 <- all_2025_size %>% 
  left_join(pheno_2025_pops) %>% 
  mutate(flower.date = lubridate::mdy(flower.date)) %>% 
  filter(!is.na(flower.date)) %>% 
  filter(survey_date==flower.date) %>% 
  select(status, Unique.ID, survey_date, flower.date, height.cm)

summary(sizeatrep_2025)

sizeatrep_2025_2025plants <- sizeatrep_2025 %>% 
  filter(status=="available") #filter to plants planted in 2025
summary(sizeatrep_2025_2025plants)
```
