---
title: "WL2_InitialSize_Establishment"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: true
---

# Checking the effects of initial size on establishment probability 
Establishment = survival first 3 weeks post transplant 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries
```{r}
library(tidyverse)
library(lme4)
```

## Load Initial Size
```{r}
initial_size <- read_csv("../input/WL2_2025_Data/CorrectedCSVs/WL2_initial_size_DNA_corrected.csv") %>% 
  mutate(Unique.ID=as.character(Unique.ID)) %>% 
  select(Unique.ID:long.leaf.cm) %>% 
  filter(!is.na(height.cm)) 
head(initial_size)

```

## Load Survival
```{r}
wl2_surv <- read_csv("../input/WL2_2025_Data/CorrectedCSVs/WL2_mort_pheno_20250929_corrected.csv") %>% 
  select(bed:Unique.ID, death.date, survey.notes)
head(wl2_surv)
```

## Load pop info
```{r}
pop_info <- read_csv("../input/WL2_2025_Data/2025_Pop_Loc_Info Updated.csv") %>% 
  select(status:Unique.ID) %>% 
  filter(status == "available")

```

## Merge
```{r}
size_surv <- left_join(wl2_surv, initial_size)

size_surv_pops <- left_join(pop_info, size_surv)
size_surv_pops %>% filter(is.na(germ.y.n))

size_surv_2025pops <- size_surv_pops %>% filter(!is.na(germ.y.n))
unique(size_surv_2025pops$death.date)
```

## Establishment
```{r}
establishment <- size_surv_2025pops %>% 
  mutate(Est_Surv=if_else(is.na(death.date), 1, 
                          if_else(death.date=="6/3/25" | death.date=="6/9/25" |
                                    death.date=="6/17/25", 0,
                                       1))) %>% 
  mutate(Pop.Type=if_else(!str_detect(pop.id, "x"), "Parent", 
                          if_else(str_detect(pop.id, "\\) x"), "F2 or BC1", "F1"))) %>% 
  select(-status, -germ.y.n)

head(establishment)
```

## Quick Plots 
```{r}
establishment %>% 
  ggplot(aes(hypocotyl.length.cm, Est_Surv)) +
  geom_point()

establishment %>% 
  ggplot(aes(height.cm, Est_Surv)) +
  geom_point()

establishment %>% 
  ggplot(aes(long.leaf.cm, Est_Surv)) +
  geom_point()
```

## PopType Averages
```{r}
est_summary <- establishment %>% 
  group_by(Pop.Type) %>% 
  summarise(meanEst=mean(Est_Surv, na.rm=TRUE), 
            meanHyp = mean(hypocotyl.length.cm, na.rm=TRUE),
            meanHeight = mean(height.cm, na.rm=TRUE), 
            meanLength = mean(long.leaf.cm, na.rm=TRUE))
est_summary
#pretty high establishment all around 
```

## Pop Averages
```{r}
est_summary_pops <- establishment %>% 
  group_by(Pop.Type, pop.id) %>% 
  summarise(meanEst=mean(Est_Surv, na.rm=TRUE), 
            meanHyp = mean(hypocotyl.length.cm, na.rm=TRUE),
            meanHeight = mean(height.cm, na.rm=TRUE), 
            meanLength = mean(long.leaf.cm, na.rm=TRUE))

est_summary_pops %>% 
  ggplot(aes(x=meanHyp, y=meanEst)) +
  geom_point() 
est_summary_pops %>% 
  ggplot(aes(x=meanHyp, y=meanEst)) +
  geom_point() + 
  facet_wrap(~Pop.Type)

est_summary_pops %>% 
  ggplot(aes(x=meanHeight, y=meanEst)) +
  geom_point() 
est_summary_pops %>% 
  ggplot(aes(x=meanHeight, y=meanEst)) +
  geom_point() + 
  facet_wrap(~Pop.Type)

est_summary_pops %>% 
  ggplot(aes(x=meanLength, y=meanEst)) +
  geom_point() 
est_summary_pops %>% 
  ggplot(aes(x=meanLength, y=meanEst)) +
  geom_point() + 
  facet_wrap(~Pop.Type)
```

## Quick Models
```{r}
hyp_for_models <- establishment %>% filter(!is.na(hypocotyl.length.cm))

hyp_est_model1 <- glm(Est_Surv ~ hypocotyl.length.cm, family=binomial, data=hyp_for_models)
summary(hyp_est_model1)

hyp_est_model2 <- glmer(Est_Surv ~ hypocotyl.length.cm + (1|Pop.Type), family=binomial, data=hyp_for_models)
summary(hyp_est_model2) #no significant relationship with hypocotyl length 
```

```{r}
height_for_models <- establishment %>% filter(!is.na(height.cm))

height_est_model1 <- glm(Est_Surv ~ height.cm, family=binomial, data=height_for_models)
summary(height_est_model1)

height_est_model2 <- glmer(Est_Surv ~ height.cm + (1|Pop.Type), family=binomial, data=height_for_models)
summary(height_est_model2) #no sig relationship with height 
```

```{r}
length_for_models <- establishment %>% filter(!is.na(long.leaf.cm))

length_est_model1 <- glm(Est_Surv ~ long.leaf.cm, family=binomial, data=length_for_models)
summary(length_est_model1)

length_est_model2 <- glmer(Est_Surv ~ long.leaf.cm + (1|Pop.Type), family=binomial, data=length_for_models)
summary(length_est_model2) #sig pos relationship with height (longer survived better)
```

## Models by Pop type 

### Parents 
```{r}
parents_est <- establishment %>% 
  filter(Pop.Type=="Parent") %>% 
  filter(!is.na(height.cm)) %>% 
  filter(!is.na(long.leaf.cm))
unique(parents_est$pop.id)

height_est_model3 <- glmer(Est_Surv ~ height.cm + (1|pop.id), family=binomial, data=parents_est)
summary(height_est_model3) #no relat

length_est_model3 <- glmer(Est_Surv ~ long.leaf.cm + (1|pop.id), family=binomial, data=parents_est)
summary(length_est_model3)

##predictions for figures:
parents_est_preds <- tibble(long.leaf.cm=seq(from = 0.2, to=4.6, length.out=185))

length_est_preds <- tibble(predictions=predict(length_est_model3, 
                                               newdata=parents_est_preds,
                                           re.form= NA, type="response")) %>% 
  bind_cols(parents_est_preds) 
length_est_preds %>% ggplot(aes(long.leaf.cm, predictions)) +
  geom_point() +
  labs(x="Leaf Length 4 Weeks Post-Strat", y="Predicted Establishment", title="Parents")
```

### Crosses 
```{r}
crosses_est <- establishment %>% 
  filter(Pop.Type!="Parent") %>% 
  filter(!is.na(height.cm)) %>% 
  filter(!is.na(long.leaf.cm))
unique(crosses_est$pop.id) #74 cross types 

height_est_model4 <- glmer(Est_Surv ~ height.cm + (1|pop.id), family=binomial, data=crosses_est)
summary(height_est_model4) #height not sig

length_est_model4 <- glmer(Est_Surv ~ long.leaf.cm + (1|pop.id), family=binomial, data=crosses_est)
summary(length_est_model4)

##predictions for figures:
crosses_est_preds <- tibble(long.leaf.cm=seq(from = 0.2, to=4.7, length.out=486))

length_est_preds <- tibble(predictions=predict(length_est_model4, 
                                               newdata=crosses_est_preds,
                                           re.form= NA, type="response")) %>% 
  bind_cols(crosses_est_preds) 
length_est_preds %>% ggplot(aes(long.leaf.cm, predictions)) +
  geom_point() +
  labs(x="Leaf Length 4 Weeks Post-Strat", y="Predicted Establishment", title="Crosses")
```
