---
title: "2024_Survival"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Checking survival the end of 2024

## Libraries
```{r}
library(tidyverse)

sem <- function(x, na.rm=FALSE) {           #for calculating standard error
  sd(x,na.rm=na.rm)/sqrt(length(na.omit(x)))
} 
```

## Surv Data
```{r}
surv_2024 <- read_csv("../input/WL2_2024_Data/CorrectedCSVs/WL2_mort_pheno_20241023_corrected.csv")
head(surv_2024)

surv_2024 %>% filter(unique.ID=="buffer") #check for buffers
```

## Pop Info
```{r}
pop_info <- read_csv("../input/WL2_2024_Data/Final_2023_2024_Pop_Loc_Info.csv") %>% 
  select(Pop.Type:unique.ID) %>% 
  rename(row=bedrow, col=bedcol)
```

## Elevation Info / Climate distance
```{r}
clim_dist_2024 <- read_csv("../output/Climate/WL2_2024_Clim_Dist.csv") %>% select(-conf.low, -conf.high)
head(clim_dist_2024)

clim_dist_2024_wide <- clim_dist_2024 %>% 
  pivot_wider(names_from = timeframe, values_from = Gowers_Dist, names_prefix = "GD_") %>% 
  rename(pop=parent.pop)
```

## Merge
```{r}
surv_2024_pops <- left_join(surv_2024, pop_info)
unique(surv_2024_pops$Pop.Type)
unique(surv_2024_pops$status)
unique(surv_2024_pops$pop)

#surv_2024_pops %>% filter(Pop.Type=="2023-TM2-fruit") #double check 2023 TM2 fruiting 
```

## Alive in Oct 2024
```{r}
alive <- surv_2024_pops %>% 
  filter(unique.ID != "buffer") %>% #remove buffers
  filter(Pop.Type!="2023-TM2-fruit") %>% #remove 2023 TM2 fruiting plants 
  filter(is.na(death.date)) %>% #keep only plants without a death date
  filter(is.na(missing.date)) %>% #keep only plants without a missing date
  mutate(deadatplanting = if_else(is.na(survey.notes), NA,
                                  if_else(survey.notes=="Dead at planting", "Yes", NA))) %>% 
  filter(is.na(deadatplanting)) #remove plants that were dead at planting 
dim(alive) #132 alive

xtabs(~Pop.Type, data=alive)
#25 parent plants from 2023 still alive
#16 F1s still alive 
#58 F2s still alive
#33 parents planted in 2024 still alive 
```

## F1 Year 1 Survival
```{r}
f1_surv<- surv_2024_pops %>% 
  mutate(Surv=if_else(is.na(death.date), 1, 0)) %>% 
  filter(Pop.Type=="F1") %>% 
  separate(pop, c("dame_pop",NA, "sire_pop"), remove = FALSE) %>% 
  select(block, loc, pop:rep, unique.ID, Surv) %>% 
  left_join(clim_dist_2024_wide, by=join_by(dame_pop==pop)) %>% 
  select(-elevation.group, -Season, -Year) %>% 
  rename(dame_elev=elev_m, dame_Lat=Lat, dame_Long=Long, dame_GD_Recent=GD_Recent, dame_GD_Historic=GD_Historic) %>% 
  left_join(clim_dist_2024_wide, by=join_by(sire_pop==pop)) %>% 
  select(-elevation.group, -Season, -Year) %>% 
  rename(sire_elev=elev_m, sire_Lat=Lat, sire_Long=Long, sire_GD_Recent=GD_Recent, sire_GD_Historic=GD_Historic) %>% 
  mutate(meanElev=(dame_elev+sire_elev)/2, 
         mean_GD_Recent=(dame_GD_Recent+sire_GD_Recent)/2, 
         mean_GD_Historic=(dame_GD_Historic+sire_GD_Historic)/2)
head(f1_surv)
  
f1_surv_summary <- f1_surv %>% 
  group_by(pop, dame_pop, dame_elev, dame_GD_Recent, dame_GD_Historic, meanElev, mean_GD_Recent, mean_GD_Historic) %>% 
  summarise(n=n(),mean_Surv=mean(Surv, na.rm=TRUE), sem_surv=sem(Surv, na.rm=TRUE)) 

f1_surv_summary %>% 
  filter(n>1) %>% 
  ggplot(aes(x=fct_reorder(pop, mean_Surv), y=mean_Surv)) + 
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.2, position = 
                  position_dodge(0.75)) +
  theme_classic() + 
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="F1 Population", y="Survival") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL2_2024_Y1Surv_F1s.png", width = 14, height = 8, units = "in")

f1_surv_summary %>% 
  filter(n>1) %>% 
  ggplot(aes(x=fct_reorder(pop, mean_Surv), y=mean_Surv, fill=dame_elev)) + 
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.2, position = 
                  position_dodge(0.75)) +
  theme_classic() + 
  scale_fill_gradient(low = "#F5A540", high = "#0043F0") +
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="F1 Population", y="Survival") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))

f1_surv_summary %>% 
  filter(n>1) %>% 
  ggplot(aes(x=fct_reorder(pop, mean_Surv), y=mean_Surv, fill=meanElev)) + 
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.2, position = 
                  position_dodge(0.75)) +
  theme_classic() + 
  scale_fill_gradient(low = "#F5A540", high = "#0043F0") +
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="F1 Population", y="Survival") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))

f1_surv_summary %>% 
  filter(n>1) %>% 
  ggplot(aes(x=mean_GD_Recent, y=mean_Surv, group=pop, colour=meanElev)) + 
  geom_point(size=6) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.02, linewidth = 2) +
  theme_classic() + 
  scale_colour_gradient(low = "#F5A540", high = "#0043F0") +
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="Parental Avg \n Recent Water Year Climate Dist", y="Survival") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL2_2024_Y1Surv_F1s_RecentCD.png", width = 14, height = 8, units = "in")

f1_surv_summary %>% 
  filter(n>1) %>% 
  ggplot(aes(x=mean_GD_Historic, y=mean_Surv, group=pop, colour=meanElev)) + 
  geom_point(size=6) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.02, linewidth = 2) +
  theme_classic() + 
  scale_colour_gradient(low = "#F5A540", high = "#0043F0") +
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="Parental Avg \n Historic Water Year Climate Dist", y="Survival") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL2_2024_Y1Surv_F1s_HistoricCD.png", width = 14, height = 8, units = "in")
```

## Parent Pops Year 1 Survival
```{r}
parent_surv<- surv_2024_pops %>% 
  mutate(Surv=if_else(is.na(death.date), 1, 0)) %>% 
  filter(Pop.Type=="Parent") %>% 
  left_join(clim_dist_2024_wide) %>% 
  select(block, loc, pop:rep, elev_m:Long, GD_Recent, GD_Historic, unique.ID, Surv)

parent_surv_summary <- parent_surv %>% 
  group_by(pop, elev_m, GD_Recent, GD_Historic) %>% 
  summarise(n=n(),mean_Surv=mean(Surv, na.rm=TRUE), sem_surv=sem(Surv, na.rm=TRUE)) 

parent_surv_summary %>% 
  filter(n>1) %>% 
  ggplot(aes(x=fct_reorder(pop, mean_Surv), y=mean_Surv, fill=elev_m)) + 
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.2, position = 
                  position_dodge(0.75)) +
  theme_classic() + 
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="Parent Population", y="Survival") +
  scale_fill_gradient(low = "#F5A540", high = "#0043F0") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL2_2024_Y1Surv_Parents.png", width = 14, height = 8, units = "in")

parent_surv_summary %>% 
  filter(n>1) %>% 
  ggplot(aes(x=GD_Recent, y=mean_Surv, group=pop, colour=elev_m)) + 
  geom_point(size=6) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.02, linewidth = 2) +
  theme_classic() + 
  scale_colour_gradient(low = "#F5A540", high = "#0043F0") +
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="Recent Water Year Climate Dist", y="Survival") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL2_2024_Y1Surv_Parents_RecentCD.png", width = 14, height = 8, units = "in")

parent_surv_summary %>% 
  filter(n>1) %>% 
  ggplot(aes(x=GD_Historic, y=mean_Surv, group=pop, colour=elev_m)) + 
  geom_point(size=6) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.02, linewidth = 2) +
  theme_classic() + 
  scale_colour_gradient(low = "#F5A540", high = "#0043F0") +
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="Historic Water Year Climate Dist", y="Survival") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL2_2024_Y1Surv_Parents_HistoricCD.png", width = 14, height = 8, units = "in")
```

## F1s + Parents
```{r}
names(parent_surv)
names(f1_surv)
parent_surv %>% 
  select(-elev_m) %>% 
  bind_rows(f1_surv) %>% 
  filter(n>2) %>% 
  ggplot(aes(x=fct_reorder(pop, mean_Surv), y=mean_Surv)) + 
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_Surv-sem_surv,ymax=mean_Surv+sem_surv),width=.2, position = 
                  position_dodge(0.75)) +
  theme_classic() + 
  scale_y_continuous(expand = c(0.01, 0)) +
  labs(x="Population", y="Survival") +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL2_Y1Surv_F1s_Parents.png", width = 14, height = 8, units = "in")
```
