---
title: "WL2_2024-2025_RxnNorms"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reaction Norms comparing differences between 2024 and 2025 at WL2

## Libraries
```{r}
library(tidyverse)

sem <- function(x, na.rm=FALSE) {  #for calculating standard error
  sd(x,na.rm=na.rm)/sqrt(length(na.omit(x)))
} 
```

## Survival Data
```{r}
year1surv_2023 <- read_csv("../../WL2.ClimDist/Processed.Data/WL2_Y1Surv.csv")

wintsurv_2024 <- read_csv("../input/WL2_2025_Data/CorrectedCSVs/WL2_overwinter_survival_20250523_corrected.csv") #contains all year 1 info too

mort_pheno_2025 <- read_csv("../input/WL2_2025_Data/CorrectedCSVs/WL2_mort_pheno_20250929_corrected.csv")
mort_pheno_2025 %>% filter(!is.na(...13)) #additional notes 
mort_pheno_2025 %>% filter(str_detect(survey.notes, "planting")) #some dead pre or at planting 
```

## Pop Info 
```{r}
pop_info_2024 <- read_csv("../input/WL2_2024_Data/Final_2023_2024_Pop_Loc_Info.csv") %>% 
  select(Pop.Type:unique.ID) %>% 
  rename(row=bedrow, col=bedcol)

pop_info_2025 <- read_csv("../input/WL2_2025_Data/2025_Pop_Loc_Info Updated.csv") %>% 
  select(status:Unique.ID)
```

## Elevation Info
```{r}
elev_info <- read_csv("../input/Strep_tort_locs.csv")

elev_info_yo <- elev_info %>% 
  mutate(pop = str_replace(`Site code`, "YOSE(\\d+)", "YO\\1")) %>% select(Lat, Long, elev_m=`Elevation (m)`, pop)
head(elev_info_yo)
unique(elev_info_yo$pop)
```

## Year 1 Survival for Parents

### 2023
```{r}
y1surv_2023_summary <- year1surv_2023 %>% 
  group_by(pop) %>% 
  summarise(meanSurv=mean(Y1Survival, na.rm=TRUE), 
            semSurv=sem(Y1Survival, na.rm=TRUE),
            N=sum(!is.na(Y1Survival))) %>% 
  left_join(elev_info_yo) %>% 
  mutate(Garden_Year = "2023")
```

### 2024
```{r}
y1surv_2024 <- wintsurv_2024 %>% 
  select(bed:unique.ID, death.date, missing.date, survey.notes) %>% 
  left_join(pop_info_2024) %>% 
  filter(unique.ID != "buffer") %>% #remove buffers
  filter(Pop.Type=="Parent") %>%  #keep only parents planted in 2024
  select(loc, bed:unique.ID, Pop.Type, pop:rep, death.date:survey.notes) %>% 
  mutate(deadatplanting = if_else(is.na(survey.notes), NA,
                                  if_else(survey.notes=="Dead at planting", "Yes", NA))) %>% 
  filter(is.na(deadatplanting)) %>% #remove plants that were dead at planting 
  filter(is.na(missing.date)) %>% #remove plants that went missing 
  select(-deadatplanting, -missing.date, -survey.notes) %>% #remove unnecessary cols 
  mutate(death.date=mdy(death.date)) %>% #convert to date format 
  mutate(Establishment = if_else(is.na(death.date), 1, 
                                 if_else(death.date < "2024-07-06", 0, 1)), #establishment = first 3 weeks post-transplant 
         Y1Surv = if_else(Establishment==0, NA, #can't survive year 1 if you didn't establish 
                          if_else(is.na(death.date), 1, 
                                        if_else(death.date < "2024-11-01", 0, 1)))) #year 1 ended in Oct

y1surv_2024_summary <- y1surv_2024 %>% 
  group_by(pop) %>% 
  summarise(meanSurv=mean(Y1Surv, na.rm=TRUE), 
            semSurv=sem(Y1Surv, na.rm=TRUE),
            N=sum(!is.na(Y1Surv))) %>% 
  left_join(elev_info_yo) %>% 
  mutate(Garden_Year = "2024")
```

### 2025
```{r}
y1surv_2025 <- mort_pheno_2025 %>% 
  select(bed:Unique.ID, bud.date, death.date, survey.notes) %>% 
  left_join(pop_info_2025) %>% 
  filter(Unique.ID!="buffer", !is.na(Unique.ID)) %>% 
  filter(status=="available") %>% #only keep plants planted in 2025
  mutate(Pop.Type=if_else(str_detect(pop.id, "\\) x"), "F2",
                          if_else(str_detect(pop.id, "x"), "F1",
                                  "Parent"
                          ))) %>% #define different pop types 
  filter(Pop.Type=="Parent") %>%  #keep only parents 
  mutate(deadatplanting = if_else(is.na(survey.notes), NA,
                                  if_else(survey.notes=="dead pre-planting" | 
                                            survey.notes=="dead at planting",
                                          "Yes", NA))) %>% 
  filter(is.na(deadatplanting)) %>% #remove plants that were dead at planting 
  select(-status, -deadatplanting, -survey.notes) %>% #remove unnecessary cols 
  mutate(death.date=mdy(death.date)) %>% #convert to date format 
  mutate(Establishment = if_else(is.na(death.date) | !is.na(bud.date), 1, 
                                 if_else(death.date < "2025-06-21", 0, 1)), #establishment = first 3 weeks post-transplant 
         Y1Surv = if_else(Establishment==0, NA, #can't survive year 1 if you didn't establish 
                          if_else(!is.na(bud.date), 1, #if you reproduced you survived 
                      if_else(is.na(death.date), 1, 0)))) 

y1surv_2025_summary <- y1surv_2025 %>% 
  rename(pop=pop.id) %>% 
  group_by(pop) %>% 
  summarise(meanSurv=mean(Y1Surv, na.rm=TRUE), 
            semSurv=sem(Y1Surv, na.rm=TRUE),
            N=sum(!is.na(Y1Surv))) %>% 
  left_join(elev_info_yo) %>% 
  mutate(Garden_Year = "2025")
```

### Reaction Norms
```{r}
y1surv_all <- y1surv_2023_summary %>% 
  bind_rows(y1surv_2024_summary) %>% 
  bind_rows(y1surv_2025_summary)
  
y1surv_all_wide <- y1surv_all %>% 
  select(pop, Garden_Year, N) %>% 
  pivot_wider(names_from = Garden_Year, values_from = N) %>% 
  mutate(All.Years=if_else(!is.na(`2025`) & !is.na(`2024`) & !is.na(`2023`), TRUE, FALSE)) %>% 
  filter(All.Years != "FALSE")

y1surv_all_years <- y1surv_all_wide %>% 
  left_join(y1surv_all) %>% 
  select(pop, meanSurv:Garden_Year)

y1surv_all_years %>% 
  filter(pop!="YO11") %>% #only 1 indiv in 2024
  ggplot(aes(x=Garden_Year, y=meanSurv, group=pop, color=elev_m)) +
  geom_point(size=1.5) + 
  geom_line(linewidth=1.5) +
  geom_errorbar(aes(ymin=meanSurv-semSurv,ymax=meanSurv+semSurv),width=.05) +
  theme_classic() + 
  scale_colour_gradient(low = "#F5A540", high = "#0043F0")  +
  labs(y="Y1 Survival", color="Elevation (m)", x="WL2 Garden Year") +
  scale_y_continuous(expand = c(0.01, 0.00)) +
  theme(text=element_text(size=28))
ggsave("../output/WL2_Traits/WL2_Y1Surv_RxNm_Parents.png", width = 14, height = 6, units = "in")

y1surv_all_years %>% 
  filter(pop!="YO11") %>% #only 1 indiv in 2024
  filter(Garden_Year!=2023) %>% 
  ggplot(aes(x=Garden_Year, y=meanSurv, group=pop, color=elev_m)) +
  geom_point(size=1.5) + 
  geom_line(linewidth=1.5) +
  geom_errorbar(aes(ymin=meanSurv-semSurv,ymax=meanSurv+semSurv),width=.05) +
  theme_classic() + 
  scale_colour_gradient(low = "#F5A540", high = "#0043F0")  +
  labs(y="Y1 Survival", color="Elevation (m)", x="WL2 Garden Year") +
  scale_y_continuous(expand = c(0.01, 0.00)) +
  theme(text=element_text(size=28))
ggsave("../output/WL2_Traits/WL2_Y1Surv_RxNm_Parents_2425.png", width = 12, height = 6, units = "in")
```

## Year 1 Survival for F1s
### 2024
```{r}
y1surv_2024_F1s <- wintsurv_2024 %>% 
  select(bed:unique.ID, death.date, missing.date, survey.notes) %>% 
  left_join(pop_info_2024) %>% 
  filter(unique.ID != "buffer") %>% #remove buffers
  filter(Pop.Type=="F1") %>%  #keep only F1s planted in 2024
  select(loc, bed:unique.ID, Pop.Type, pop:rep, death.date:survey.notes) %>% 
  mutate(deadatplanting = if_else(is.na(survey.notes), NA,
                                  if_else(survey.notes=="Dead at planting", "Yes", NA))) %>% 
  filter(is.na(deadatplanting)) %>% #remove plants that were dead at planting 
  filter(is.na(missing.date)) %>% #remove plants that went missing 
  select(-deadatplanting, -missing.date, -survey.notes) %>% #remove unnecessary cols 
  mutate(death.date=mdy(death.date)) %>% #convert to date format 
  mutate(Establishment = if_else(is.na(death.date), 1, 
                                 if_else(death.date < "2024-07-06", 0, 1)), #establishment = first 3 weeks post-transplant 
         Y1Surv = if_else(Establishment==0, NA, #can't survive year 1 if you didn't establish 
                          if_else(is.na(death.date), 1, 
                                        if_else(death.date < "2024-11-01", 0, 1)))) #year 1 ended in Oct

y1surv_2024_F1s_summary <- y1surv_2024_F1s %>% 
  group_by(pop) %>% 
  summarise(meanSurv=mean(Y1Surv, na.rm=TRUE), 
            semSurv=sem(Y1Surv, na.rm=TRUE),
            N=sum(!is.na(Y1Surv))) %>% 
  mutate(Garden_Year = "2024")
```

### 2025
```{r}
y1surv_2025_F1s <- mort_pheno_2025 %>% 
  select(bed:Unique.ID, bud.date, death.date, survey.notes) %>% 
  left_join(pop_info_2025) %>% 
  filter(Unique.ID!="buffer", !is.na(Unique.ID)) %>% 
  filter(status=="available") %>% #only keep plants planted in 2025
  mutate(Pop.Type=if_else(str_detect(pop.id, "\\) x"), "F2",
                          if_else(str_detect(pop.id, "x"), "F1",
                                  "Parent"
                          ))) %>% #define different pop types 
  filter(Pop.Type=="F1") %>%  #keep only F1s 
  mutate(deadatplanting = if_else(is.na(survey.notes), NA,
                                  if_else(survey.notes=="dead pre-planting" | 
                                            survey.notes=="dead at planting",
                                          "Yes", NA))) %>% 
  filter(is.na(deadatplanting)) %>% #remove plants that were dead at planting 
  select(-status, -deadatplanting, -survey.notes) %>% #remove unnecessary cols 
  mutate(death.date=mdy(death.date)) %>% #convert to date format 
  mutate(Establishment = if_else(is.na(death.date) | !is.na(bud.date), 1, 
                                 if_else(death.date < "2025-06-21", 0, 1)), #establishment = first 3 weeks post-transplant 
         Y1Surv = if_else(Establishment==0, NA, #can't survive year 1 if you didn't establish 
                          if_else(!is.na(bud.date), 1, #if you reproduced you survived 
                      if_else(is.na(death.date), 1, 0)))) 

y1surv_2025_F1s_summary <- y1surv_2025_F1s %>% 
  rename(pop=pop.id) %>% 
  group_by(pop) %>% 
  summarise(meanSurv=mean(Y1Surv, na.rm=TRUE), 
            semSurv=sem(Y1Surv, na.rm=TRUE),
            N=sum(!is.na(Y1Surv))) %>% 
  mutate(Garden_Year = "2025")
```

### Reaction Norm
```{r}
y1surv_all_F1s <- y1surv_2024_F1s_summary %>% 
  bind_rows(y1surv_2025_F1s_summary) 
  
y1surv_all_F1s_wide <- y1surv_all_F1s %>% 
  select(pop, Garden_Year, N) %>% 
  pivot_wider(names_from = Garden_Year, values_from = N) %>% 
  mutate(All.Years=if_else(!is.na(`2025`) & !is.na(`2024`), TRUE, FALSE)) %>% 
  filter(All.Years != "FALSE") 
dim(y1surv_all_F1s_wide) #only 5 F1s

y1surv_all_F1s_years <- y1surv_all_F1s_wide %>% 
  left_join(y1surv_all_F1s) %>% 
  select(pop, meanSurv:Garden_Year) %>% 
  separate(pop, c("Pop1", "Pop2"), sep = " x ", remove = FALSE) %>% 
  left_join(elev_info_yo, by=join_by(Pop1==pop))
y1surv_all_F1s_years

y1surv_all_F1s_years %>% 
  ggplot(aes(x=Garden_Year, y=meanSurv, group=pop, color=elev_m)) +
  geom_point(size=1.5) + 
  geom_line(linewidth=1.5) +
  geom_errorbar(aes(ymin=meanSurv-semSurv,ymax=meanSurv+semSurv),width=.05) +
  theme_classic() + 
  scale_colour_gradient(low = "#F5A540", high = "#0043F0")  +
  labs(y="Y1 Survival", color="Elevation (m) \n of Donor", x="WL2 Garden Year") +
  scale_y_continuous(expand = c(0.01, 0.00)) +
  theme(text=element_text(size=28))
ggsave("../output/WL2_Traits/WL2_Y1Surv_RxNm_F1s.png", width = 14, height = 6, units = "in")
```

## Size Post-Establishment
```{r}
size_2023 <- read_csv("../../parent_pops_common-gardens/input/WL2_Data/CorrectedCSVs/WL2_size_survey_20230816_corrected.csv") %>% 
  select(pop:height.cm) %>% 
  filter(pop!="buffer", 
         !str_detect(pop, "\\*"))

size_2024 <- read_csv("../input/WL2_2024_Data/CorrectedCSVs/WL2_size_survey_20240709_corrected.csv") %>% 
  filter(unique.ID != "buffer") %>% #remove buffers
  select(unique.ID:height.cm) %>% 
  left_join(pop_info_2024) %>% 
  filter(Pop.Type=="Parent")  #keep only parents planted in 2024

size_2025 <- read_csv("../input/WL2_2025_Data/CorrectedCSVs/WL2_size_survey_20250627_corrected.csv") %>% 
  filter(Unique.ID != "buffer") %>% #remove buffers
  select(Unique.ID:height.cm) %>% 
  left_join(pop_info_2025) %>% 
  filter(status=="available") %>% #only keep plants planted in 2025
  mutate(Pop.Type=if_else(str_detect(pop.id, "\\) x"), "F2",
                          if_else(str_detect(pop.id, "x"), "F1",
                                  "Parent"
                          ))) %>% #define different pop types 
  filter(Pop.Type=="Parent") #keep only parents 
```

### Pop Summaries
```{r}
size_2023_summary <- size_2023 %>% 
  mutate(height.cm=as.numeric(height.cm)) %>% 
  group_by(pop) %>% 
  summarise(meanHeight=mean(height.cm, na.rm=TRUE),
            semHeight=sem(height.cm, na.rm = TRUE),
            nHeight=sum(!is.na(height.cm))) %>% 
  mutate(Garden_Year = "2023")

size_2024_summary <- size_2024 %>% 
  group_by(pop) %>% 
  summarise(meanHeight=mean(height.cm, na.rm=TRUE),
            semHeight=sem(height.cm, na.rm = TRUE),
            nHeight=sum(!is.na(height.cm))) %>% 
  mutate(Garden_Year = "2024")

size_2025_summary <- size_2025 %>% 
  rename(pop=pop.id) %>% 
  group_by(pop) %>% 
  summarise(meanHeight=mean(height.cm, na.rm=TRUE),
            semHeight=sem(height.cm, na.rm = TRUE),
            nHeight=sum(!is.na(height.cm))) %>% 
  mutate(Garden_Year = "2025")

all_size <- size_2023_summary %>% 
  bind_rows(size_2024_summary) %>% 
  bind_rows(size_2025_summary) %>% 
  right_join(y1surv_all_wide) %>% 
  select(pop:nHeight, Garden_Year) %>% 
  left_join(elev_info_yo)
```

### Reaction Norms
```{r}
all_size %>% 
  filter(pop!="LV1", pop!="YO11") %>% #only 1 indiv in 2024  
  ggplot(aes(x=Garden_Year, y=meanHeight, group=pop, color=elev_m)) +
  geom_point(size=1.5) + 
  geom_line(linewidth=1.5) +
  geom_errorbar(aes(ymin=meanHeight-semHeight,ymax=meanHeight+semHeight),width=.05) +
  theme_classic() + 
  scale_colour_gradient(low = "#F5A540", high = "#0043F0")  +
  labs(y="Height (cm)", color="Elevation (m)", x="WL2 Garden Year") +
  scale_y_continuous(expand = c(0.01, 0.00)) +
  theme(text=element_text(size=28))
ggsave("../output/WL2_Traits/WL2_Height_RxNm_Parents.png", width = 14, height = 6, units = "in")
```

### F1s Height
```{r}
size_2024_F1s <- read_csv("../input/WL2_2024_Data/CorrectedCSVs/WL2_size_survey_20240709_corrected.csv") %>% 
  filter(unique.ID != "buffer") %>% #remove buffers
  select(unique.ID:height.cm) %>% 
  left_join(pop_info_2024) %>% 
  filter(Pop.Type=="F1" | pop=="WL2")  #keep only parents planted in 2024

size_2025_F1s <- read_csv("../input/WL2_2025_Data/CorrectedCSVs/WL2_size_survey_20250627_corrected.csv") %>% 
  filter(Unique.ID != "buffer") %>% #remove buffers
  select(Unique.ID:height.cm) %>% 
  left_join(pop_info_2025) %>% 
  filter(status=="available") %>% #only keep plants planted in 2025
  mutate(Pop.Type=if_else(str_detect(pop.id, "\\) x"), "F2",
                          if_else(str_detect(pop.id, "x"), "F1",
                                  "Parent"
                          ))) %>% #define different pop types 
  filter(Pop.Type=="F1" | pop.id=="WL2") #keep only parents
```

```{r}
size_2024_F1s_summary <- size_2024_F1s %>% 
  group_by(pop) %>% 
  summarise(meanHeight=mean(height.cm, na.rm=TRUE),
            semHeight=sem(height.cm, na.rm = TRUE),
            nHeight=sum(!is.na(height.cm))) %>% 
  separate(pop, c("Pop1", "Pop2"), sep = " x ", remove = FALSE) %>% 
  filter(Pop2=="WL2" | is.na(Pop2)) %>% 
  left_join(elev_info_yo, by=join_by(Pop1==pop))

size_2025_F1s_summary <- size_2025_F1s %>% 
  rename(pop=pop.id) %>% 
  group_by(pop) %>% 
  summarise(meanHeight=mean(height.cm, na.rm=TRUE),
            semHeight=sem(height.cm, na.rm = TRUE),
            nHeight=sum(!is.na(height.cm))) %>% 
  separate(pop, c("Pop1", "Pop2"), sep = " x ", remove = FALSE) %>% 
  mutate(other_Parent=if_else(is.na(Pop2), "WL2",
                              if_else(Pop1=="WL2", Pop2, Pop1))) %>% 
  left_join(elev_info_yo, by=join_by(other_Parent==pop))
```

```{r}
size_2024_F1s_summary %>% 
  filter(nHeight>1) %>% 
  ggplot(aes(x=fct_reorder(pop, meanHeight), y=meanHeight, group = pop, fill=elev_m)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=meanHeight-semHeight,ymax=meanHeight+semHeight),
                width=.05, position = position_dodge(0.75)) +
  theme_classic() + 
  scale_fill_gradient(low = "#F5A540", high = "#0043F0")  +
  labs(y="Height (cm)", fill="Elevation (m) \n of Donor", x="F1 Cross") +
  scale_y_continuous(expand = c(0.01, 0.00)) +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL22024_Height_WL2F1s.png", width = 14, height = 8, units = "in")
```

```{r}
size_2025_F1s_summary %>% 
  filter(nHeight>1) %>% 
  ggplot(aes(x=fct_reorder(pop, meanHeight), y=meanHeight, group = pop, fill=elev_m)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=meanHeight-semHeight,ymax=meanHeight+semHeight),
                width=.05, position = position_dodge(0.75)) +
  theme_classic() + 
  scale_fill_gradient(low = "#F5A540", high = "#0043F0")  +
  labs(y="Height (cm)", fill="Elevation (m) \n of Donor", x="F1 Cross") +
  scale_y_continuous(expand = c(0.01, 0.00)) +
  theme(text=element_text(size=25), axis.text.x = element_text(angle = 45, hjust = 1))
ggsave("../output/WL2_Traits/WL22025_Height_WL2F1s.png", width = 14, height = 6, units = "in")
```

